### ISSUE TITLE
the successfully executed command has its output redirected to stderr.

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/ckb-cli#558]
```
./ckb-cli --version
ckb-cli 1.4.0 (33bd1a1 2023-03-27)
guopenglin@MacBook-Pro-4 0.111.0 % export API_URL=http://127.0.0.1:8115 && cd /Users/guopenglin/WebstormProjects/gp/ckb-py-integration-test/download/0.111.0 && ./ckb-cli tx init --tx-file /tmp/tx.txt > demo.log 2>demo.err.log 
guopenglin@MacBook-Pro-4 0.111.0 % cat demo.log 
guopenglin@MacBook-Pro-4 0.111.0 % cat demo.err.log 
status: success
```

**Comment by yangby-cryptape** [comment]
### Brief Answer

I suggested that in issue #288.

### Details

I could understand your confusion.
You must be had a misunderstanding with its literal meaning: "`stderr` is used for errors only".

In fact, the `stderr` is used for printing **things which are not outputs**, so users could use pipes easily.

That is a very traditional practice. There are lots examples in the real world.

For examples:

- `curl` (since 1996)

  ```shell
  curl --verbose --location www.github.com >stdout.log 2>stderr.log
  ```

- `jq` (since 2012)

  ```
  echo '{ "id": "yangby-cryptape", "age": 46, "hobby": ["drink coke", "play with dogs", "sleep"] }' \
      | jq ".hobby[2] | debug" >stdout.log 2>stderr.log
  ```

Both `curl` and `jq` are very famous open-source projects, and they are started in different decades.
And they both use `stdout` for outputs and `stderr` for debug messages. 
 
As a reference, I copied [some documentation from `jq` Manual](https://jqlang.github.io/jq/manual/#IO).

>  ... (Recall that a jq program's output values are always output as JSON texts on stdout.) ... The stderr builtin outputs its input in raw mode to stder with no additional decoration, not even a newline.
